🧹 chore:
  - '^(\[chore\])'
📚 docs:
  - '^(\[docs\])'
🚀 feat:
  - '^(\[feat\])'
🐞 fix:
  - '^(\[fix\])'
🔨 refactor:
  - '^(\[refactor\])'
🎨 style:
  - '^(\[style\])'
✅ test:
  - '^(\[test\])'
⚙️ utils:
  - '^(\[utils\])'