name: PR을 프로젝트에 자동 할당합니다.

on:
  pull_request:
    types: [opened,reopened]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add PR to project
        uses: github/add-to-project@v1
        with:
          project-url: https://github.com/orgs/devlink-community/projects/4
          github-token: ${{ secrets.GITHUB_TOKEN }}
