name: PR을 프로젝트에 자동 할당합니다.

on:
  pull_request:
    types: [opened, reopened]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  add-pr-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Setup GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh
          echo "${{ secrets.JIYOUNG_PAT }}" | gh auth login --with-token

      - name: Add PR to Project
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          gh project item-add 4 --owner devlink-community --url "$PR_URL"
