name: PR을 프로젝트에 자동 할당합니다.

on:
  pull_request:
    types: [opened, reopened]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Set up GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Check GitHub CLI login
        run: gh auth status

      - name: Add PR to project
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          gh project item-add 4 --owner devlink-community --url https://github.com/devlink-community/devlink-mobile-app/pull/$PR_NUMBER
