name: 이슈를 프로젝트에 자동 할당합니다.

on:
  issues:
    types: [opened]

permissions:
  contents: read
  issues: write

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Setup GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Add Issue to Project
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          gh project item-add 4 --owner devlink-community --url https://github.com/devlink-community/devlink-mobile-app/issues/$ISSUE_NUMBER
