name: PR 작성자를 담당자로 지정합니다.

on:
  pull_request:
    types: [opened,reopened]

permissions:
  issues: write

jobs:
  assign-pr-author:
    runs-on: ubuntu-latest
    steps:
      - name: Assign PR to creator
        uses: actions/github-script@v7
        with:
          script: |
            const creator = context.payload.pull_request.user.login;
            await github.rest.issues.addAssignees({
              ...context.repo,
              issue_number: context.payload.pull_request.number,
              assignees: [creator],
            });
