name: issue를 만든 사람을 담당자로 지정합니다.

on:
  issues:
    types: [opened]

permissions:
  contents: read
  issues: write
  

jobs:
  assign-creator:
    runs-on: ubuntu-latest
    steps:
      - name: Assign issue to creator
        uses: actions-ecosystem/action-assign-to-creator@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
